font_size_ref_range: [0.85, 1.15]
font_size_fallback: [16, 32]
font_size_relax_min: 12
font_size_estimate_bias: 1.1
line_spacing_default: 1.2
line_spacing_compact: 1.1
line_spacing_compact_threshold: 0.9
